### ISSUE TITLE
Need to run `pulp` to build the Purescript code

### ISSUE THREAD

**Issue by noelwelsh** [lumihq/react-basic-starter#1]
It seems the getting started instructions are missing a step or npm (or webpack) is not configured correctly. Following the instructions as written does not work for me. I see an error in the browser console that the webpack main function is not defined. I assume this refers to `main` defined in `Main.purs` not being built. I got around this by running `pulp build`. 

So possible solutions:

* add instructions to run `pulp build`; or
* change the npm `start` command to also build the Purescript code

I'm completely new to Purescript and almost as new to npm and webpack, so maybe I'm misunderstanding what is supposed to happen here.

**Comment by spicydonuts** [comment]
Hmm, the steps as listed work for me. Webpack us using `purs-loader` to build the PureScript code. Running `pulp build` shouldn't hurt though.

**Comment by noelwelsh** [comment]
🤷‍♀️Since I basically have no clue how any of this stuff works might as well close this. I'll reopen if I ever work out the exact issue. Thanks for looking into it.
